### ISSUE TITLE
Check typos [feature request]

### ISSUE THREAD

**Issue by lexfrei** [nixargh/sheetocan#7]
Please add string validating with something like this:

 `^201\d-(0[1-9]|1[0-2])-(0[1-9]|[1-2]\d|3[0-1]),([0-1]\d|2[0-3]):[0-5]\d,([0-1]\d|2[0-3]):[0-5]\d,[\w-]+,RT:\d{6},"(.*)"$`

Coz today i got typos like

> 2016-02-04,22:00,**3**3:03,XXXXXX,RT:NNNNNN,"Deploy"

&

> 2016-02-04,22:00,23:03,XXXXXX,RT:NNNNNN,"Deplo"**y**

but sheetocan doesn't warn me.

**Comment by nixargh** [comment]
Sheetocan doesn't care about description like "Deplo"**y**, ticket's number and queue. But it cares about proper time calculation, so i'll add some check of date and time.
About other things you will be warned by falcon during commit.

**Comment by paskal** [comment]
Still it will be nice thing to have, doesn't seems that costy but should be useful for manual edits.

**Comment by lexfrei** [comment]
> About other things you will be warned by falcon during commit.

It was hard to find date type when falcon reported about.
Falcon doesn't reported about 'deplo"y', so i found it by my self in previous month. Now i can't reproduce error with no report, but it was.

**Comment by nixargh** [comment]
**Date, time and ticket name validation were added at** [480f902](https://github.com/nixargh/sheetocan/commit/480f90288cfe63492d0020811bb80ede30729b3a) **commit.**
But i'm not going to do something for description because sheetocan takes all after last comma as description and removes `"` signs. So it can't check `"` position at validation stage.
Technically i could change current behavior but i don't think typos at description deserves this efforts.

Closing this issue.
